import { Lang } from "@/core/types";

export const COUNTRIES: Lang<{ countryId: string; countryName: string }> = {
  es: [
    { countryId: "country_1", countryName: "Colombia" },
    { countryId: "country_2", countryName: "Estados Unidos" },
    { countryId: "country_3", countryName: "España" },
    { countryId: "country_4", countryName: "México" },
    { countryId: "country_5", countryName: "El Salvador" },
    { countryId: "country_6", countryName: "Venezuela" },
    { countryId: "country_7", countryName: "Honduras" },
    { countryId: "country_8", countryName: "Ecuador" },
    { countryId: "country_9", countryName: "Chile" },
    { countryId: "country_10", countryName: "Brasil" },
    { countryId: "country_11", countryName: "Uruguay" },
    { countryId: "country_12", countryName: "Paraguay" },
    { countryId: "country_13", countryName: "Perú" },
    { countryId: "country_14", countryName: "Bolivia" },
    { countryId: "country_15", countryName: "Argentina" },
    { countryId: "country_16", countryName: "Nicaragua" },
    { countryId: "country_17", countryName: "Puerto Rico" },
    { countryId: "country_18", countryName: "Panamá" },
    { countryId: "country_19", countryName: "República Dominicana" },
    { countryId: "country_20", countryName: "Guatemala" },
    { countryId: "country_21", countryName: "Costa Rica" },
    { countryId: "country_22", countryName: "Cuba" },
    { countryId: "country_23", countryName: "Haití" },
    { countryId: "country_24", countryName: "Jamaica" },
    { countryId: "country_25", countryName: "Belice" },
    { countryId: "country_26", countryName: "Guyana" },
    { countryId: "country_27", countryName: "Surinam" },
    { countryId: "country_28", countryName: "Trinidad y Tobago" },
  ],
  en: [
    { countryId: "country_1", countryName: "Colombia" },
    { countryId: "country_2", countryName: "United States" },
    { countryId: "country_3", countryName: "Spain" },
    { countryId: "country_4", countryName: "Mexico" },
    { countryId: "country_5", countryName: "El Salvador" },
    { countryId: "country_6", countryName: "Venezuela" },
    { countryId: "country_7", countryName: "Honduras" },
    { countryId: "country_8", countryName: "Ecuador" },
    { countryId: "country_9", countryName: "Chile" },
    { countryId: "country_10", countryName: "Brazil" },
    { countryId: "country_11", countryName: "Uruguay" },
    { countryId: "country_12", countryName: "Paraguay" },
    { countryId: "country_13", countryName: "Peru" },
    { countryId: "country_14", countryName: "Bolivia" },
    { countryId: "country_15", countryName: "Argentina" },
    { countryId: "country_16", countryName: "Nicaragua" },
    { countryId: "country_17", countryName: "Puerto Rico" },
    { countryId: "country_18", countryName: "Panama" },
    { countryId: "country_19", countryName: "Dominican Republic" },
    { countryId: "country_20", countryName: "Guatemala" },
    { countryId: "country_21", countryName: "Costa Rica" },
    { countryId: "country_22", countryName: "Cuba" },
    { countryId: "country_23", countryName: "Haiti" },
    { countryId: "country_24", countryName: "Jamaica" },
    { countryId: "country_25", countryName: "Belize" },
    { countryId: "country_26", countryName: "Guyana" },
    { countryId: "country_27", countryName: "Suriname" },
    { countryId: "country_28", countryName: "Trinidad and Tobago" },
  ],
  pt: [
    { countryId: "country_1", countryName: "Colômbia" },
    { countryId: "country_2", countryName: "Estados Unidos" },
    { countryId: "country_3", countryName: "Espanha" },
    { countryId: "country_4", countryName: "México" },
    { countryId: "country_5", countryName: "El Salvador" },
    { countryId: "country_6", countryName: "Venezuela" },
    { countryId: "country_7", countryName: "Honduras" },
    { countryId: "country_8", countryName: "Equador" },
    { countryId: "country_9", countryName: "Chile" },
    { countryId: "country_10", countryName: "Brasil" },
    { countryId: "country_11", countryName: "Uruguai" },
    { countryId: "country_12", countryName: "Paraguai" },
    { countryId: "country_13", countryName: "Peru" },
    { countryId: "country_14", countryName: "Bolívia" },
    { countryId: "country_15", countryName: "Argentina" },
    { countryId: "country_16", countryName: "Nicarágua" },
    { countryId: "country_17", countryName: "Porto Rico" },
    { countryId: "country_18", countryName: "Panamá" },
    { countryId: "country_19", countryName: "República Dominicana" },
    { countryId: "country_20", countryName: "Guatemala" },
    { countryId: "country_21", countryName: "Costa Rica" },
    { countryId: "country_22", countryName: "Cuba" },
    { countryId: "country_23", countryName: "Haiti" },
    { countryId: "country_24", countryName: "Jamaica" },
    { countryId: "country_25", countryName: "Belize" },
    { countryId: "country_26", countryName: "Guiana" },
    { countryId: "country_27", countryName: "Suriname" },
    { countryId: "country_28", countryName: "Trinidad e Tobago" },
  ],
};
