export const COUNTRIES = [
  { countryId: "country_1", countryName: "Colombia" },
  { countryId: "country_2", countryName: "Estados Unidos" },
  { countryId: "country_3", countryName: "España" },
  { countryId: "country_4", countryName: "México" },
  { countryId: "country_5", countryName: "El Salvador" },
  { countryId: "country_6", countryName: "Venezuela" },
  { countryId: "country_7", countryName: "Honduras" },
  { countryId: "country_8", countryName: "Ecuador" },
  { countryId: "country_9", countryName: "Chile" },
  { countryId: "country_10", countryName: "Brasil" },
  { countryId: "country_11", countryName: "Uruguay" },
  { countryId: "country_12", countryName: "Paraguay" },
  { countryId: "country_13", countryName: "Perú" },
  { countryId: "country_14", countryName: "Bolivia" },
  { countryId: "country_15", countryName: "Argentina" },
  { countryId: "country_16", countryName: "Nicaragua" },
  { countryId: "country_17", countryName: "Puerto Rico" },
  { countryId: "country_18", countryName: "Panamá" },
  { countryId: "country_19", countryName: "República Dominicana" },
];
